# Generated by Django 3.2.3 on 2021-05-22 03:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('last_name_kana', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=30)),
                ('first_name_kana', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredStaff',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('staff_id', models.IntegerField()),
                ('last_name', models.CharField(max_length=30)),
                ('last_name_kana', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=30)),
                ('first_name_kana', models.CharField(max_length=60)),
                ('registered_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('interviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobByDay',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.registeredstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('splittable', models.BooleanField(default=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('assigned_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.registeredstaff')),
            ],
        ),
    ]
