# Generated by Django 3.2.3 on 2021-05-26 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesSetting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GatheringPlaceSetting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('start_hour', models.CharField(blank=True, max_length=5, null=True)),
                ('end_hour', models.CharField(blank=True, max_length=5, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('unspecified', models.IntegerField(blank=True, null=True)),
                ('clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clothessetting')),
                ('gathering_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gatheringplacesetting')),
            ],
        ),
        migrations.CreateModel(
            name='PositionGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('position_color', models.CharField(max_length=10)),
                ('default_position_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.positiondata')),
                ('positions', models.ManyToManyField(related_name='position_group', to='api.Position')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobbyday',
            name='assigned_staff',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobByDay',
        ),
        migrations.AddField(
            model_name='position',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.positiondata'),
        ),
        migrations.AddField(
            model_name='event',
            name='position_groups',
            field=models.ManyToManyField(related_name='event', to='api.PositionGroup'),
        ),
    ]
