# Generated by Django 3.2.3 on 2021-05-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredstaff',
            name='interviewed_by',
        ),
        migrations.AlterField(
            model_name='registeredstaff',
            name='staff_id',
            field=models.CharField(max_length=30),
        ),
    ]
