# Generated by Django 3.2.3 on 2021-06-07 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210531_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at_datetime', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(default='')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registeredstaff')),
            ],
        ),
        migrations.CreateModel(
            name='MailsForEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('associated_data', models.TextField(default='{}')),
                ('template', models.TextField(default='')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='api.event')),
                ('mails', models.ManyToManyField(to='api.Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applied_at_date', models.DateField(auto_created=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('applied_to_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registeredstaff')),
            ],
        ),
    ]
