# Generated by Django 3.2.3 on 2021-05-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210527_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiondata',
            name='nullable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
