# Generated by Django 3.2.3 on 2021-05-29 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_positiondata_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredstaff',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredstaff',
            name='email_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredstaff',
            name='telephone_number',
            field=models.CharField(default='012-345-678910', max_length=30),
            preserve_default=False,
        ),
    ]
