# Generated by Django 3.2.3 on 2021-05-29 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210529_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=10)),
            ],
        ),
    ]
