# Generated by Django 3.2.3 on 2021-06-07 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210608_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
