# Generated by Django 3.2.3 on 2021-05-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredstaff',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.gender'),
        ),
    ]
