# Generated by Django 3.2.3 on 2021-05-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registeredstaff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstaff',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unspecified', '未指定')], default='male', max_length=20),
            preserve_default=False,
        ),
    ]
