# Generated by Django 3.2.3 on 2021-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_registeredstaff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='assignedStaffs',
            field=models.ManyToManyField(related_name='position', to='api.RegisteredStaff'),
        ),
    ]
