# Generated by Django 3.2.3 on 2021-05-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_position_assignedstaffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='assignedStaffs',
            new_name='assigned_staffs',
        ),
    ]
